spring:
  application:
     name: SpringBoot_LocaitonSevices

redis:
    host: localhost
    port: '6379'



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true





